import turtle as trtl

wn = trtl.Screen()


gary = trtl.Turtle()
gary.pencolor("pink")
gary.forward(50)
gary.right(90)
gary.forward(70)
gary.right(90)
gary.forward(50)
gary.right(90)
gary.forward(70)
gary.right(180)
gary.forward(70)
gary.left(90)
gary.forward(50)
gary.pencolor("blue")
gary.forward(30)
gary.left(90)
gary.forward(30)
gary.left(90)
gary.forward(30)
gary.right(180)
gary.forward(10)
gary.goto(60,40)
gary.circle(15)
gary.right(90)
gary.forward(80)
gary.right(10)
gary.goto(90,40)
gary.circle(15)




gary.clear()
gary = trtl.Turtle()
gary.pencolor("pink")
gary.forward(50)
gary.right(90)
gary.forward(70)
gary.right(90)
gary.forward(50)
gary.right(90)
gary.forward(70)
gary.right(180)
gary.forward(70)
gary.left(90)
gary.forward(50)
gary.pencolor("blue")
gary.forward(30)
gary.left(90)
gary.forward(30)
gary.left(90)
gary.forward(30)
gary.right(180)
gary.forward(10)
gary.goto(60,40)
gary.fillcolor("blue")
gary.begin_fill()
gary.circle(15)
gary.end_fill()
gary.right(90)
gary.forward(80)
gary.right(10)
gary.goto(90,40)
gary.fillcolor("blue")
gary.begin_fill()
gary.circle(15)
gary.end_fill()


gary.clear()
gary = trtl.Turtle()
gary.pencolor("pink")
gary.forward(50)
gary.right(90)
gary.forward(70)
gary.right(90)
gary.forward(50)
gary.right(90)
gary.forward(70)
gary.right(180)
gary.forward(70)
gary.left(90)
gary.forward(50)
gary.pencolor("blue")
gary.forward(30)
gary.left(90)
gary.forward(30)
gary.left(90)
gary.forward(30)
gary.right(180)
gary.forward(10)
gary.goto(60,40)
gary.circle(15)
gary.right(90)
gary.forward(80)
gary.right(10)
gary.goto(90,40)
gary.circle(15)


wn.mainloop()